# Generated by Django 5.0.2 on 2024-05-10 12:33

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_other_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_tel',
            field=models.CharField(max_length=10, validators=[main.validators.check_phone_number], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='productproperties',
            name='weight',
            field=models.CharField(max_length=50, verbose_name='Вес'),
        ),
    ]
